version: "3"

services:
  catcat-qrservice:
    container_name: catcat-qrservice
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - PORT=${PORT:-9095}
      - PM2_PORT=${PM2_PORT:-8095}
    image: catcatio/qrservice
    working_dir: /usr/app
    ports:
      - "${PORT:-9095}:${PORT:-9095}"
      - "${PM2_PORT:-8095}:${PM2_PORT:-8095}"
    volumes:
      - .:/usr/app
    command: sh scripts/startup.sh
